# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-26 09:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farm_to_pocket', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
                ('phonenumber', models.CharField(max_length=20, null=True)),
                ('level', models.IntegerField(null=True)),
                ('location', models.CharField(max_length=50)),
                ('nearest_town', models.CharField(max_length=50)),
                ('product', models.CharField(max_length=50)),
                ('quantity', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('availability', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('availability', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
                ('phonenumber', models.CharField(max_length=20, null=True)),
                ('level', models.IntegerField(null=True)),
                ('location', models.CharField(max_length=50)),
                ('nearest_town', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farm_to_pocket.Seller'),
        ),
    ]
