# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-26 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_to_pocket', '0003_auto_20180226_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='price',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
