# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-28 12:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farm_to_pocket', '0004_auto_20180226_1856'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
                ('type_of_user', models.CharField(max_length=2, null=True)),
                ('phonenumber', models.CharField(max_length=20, null=True)),
                ('level', models.IntegerField(null=True)),
                ('location', models.CharField(max_length=50)),
                ('nearest_town', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Buyer',
        ),
        migrations.RemoveField(
            model_name='product',
            name='seller',
        ),
        migrations.DeleteModel(
            name='Seller',
        ),
        migrations.AddField(
            model_name='product',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='farm_to_pocket.User'),
        ),
    ]
