# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-01 04:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farm_to_pocket', '0005_auto_20180228_1543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='availability',
        ),
    ]
