# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-01 04:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_to_pocket', '0006_remove_product_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='availability',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
