# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-01 07:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farm_to_pocket', '0009_product_availability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='availability',
        ),
    ]
