# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-07 05:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_to_pocket', '0010_remove_product_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='type_of_product',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
