# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-02 10:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farm_to_pocket', '0010_remove_product_availability'),
        ('farm_to_pocket', '0003_auto_20180227_1509'),
    ]

    operations = [
    ]
