# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-07 05:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_to_pocket', '0012_remove_user_type_of_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='type_of_user',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
